# Pytorch

##  Testing Installation

If the code cell shows an error, then your PyTorch installation is not working and you should bug me..

In [1]:
### Code Cell to Test PyTorch

import torch
print(torch.__version__)
import torchvision
import torchvision.transforms as transforms
print(torchvision.__version__)

x = torch.rand(5, 3)
print(x)

transforms.RandomRotation(0.7)
transforms.RandomRotation([0.9, 0.2])

t = transforms.RandomRotation(10)
angle = t.get_params(t.degrees)

print(angle)


1.0.0
0.2.1
tensor([[0.3076, 0.3248, 0.7830],
        [0.9113, 0.3061, 0.4001],
        [0.2532, 0.7230, 0.3486],
        [0.0468, 0.8159, 0.7262],
        [0.8243, 0.9483, 0.2627]])
-3.2875803472431775


## Why PyTorch?

*All the quotes will come from the PyTorch About Page http://pytorch.org/about/ from which we'll plagiarize shamelessly.  After all, who better to tout the virtues of PyTorch than the creators?*


### What is PyTorch?

According to the PyTorch about page, "PyTorch is a python package that provides two high-level features:

- Tensor computation (like numpy) with strong GPU acceleration
- Deep Neural Networks built on a tape-based autograd system"

### Why is it getting so popular?

#### It's quite fast

"PyTorch has minimal framework overhead. We integrate acceleration libraries such as Intel MKL and NVIDIA (CuDNN, NCCL) to maximize speed. At the core, it’s CPU and GPU Tensor and Neural Network backends (TH, THC, THNN, THCUNN) are written as independent libraries with a C99 API.
They are mature and have been tested for years.

Hence, PyTorch is quite fast – whether you run small or large neural networks."

#### Imperative programming experience

"PyTorch is designed to be intuitive, linear in thought and easy to use. When you execute a line of code, it gets executed. There isn’t an asynchronous view of the world. When you drop into a debugger, or receive error messages and stack traces, understanding them is straight-forward. The stack-trace points to exactly where your code was defined. We hope you never spend hours debugging your code because of bad stack traces or asynchronous and opaque execution engines."

"PyTorch is not a Python binding into a monolothic C++ framework. It is built to be deeply integrated into Python. You can use it naturally like you would use numpy / scipy / scikit-learn etc. You can write your new neural network layers in Python itself, using your favorite libraries and use packages such as Cython and Numba. Our goal is to not reinvent the wheel where appropriate."

#### Takes advantage of GPUs easily

"PyTorch provides Tensors that can live either on the CPU or the GPU, and accelerate compute by a huge amount.

We provide a wide variety of tensor routines to accelerate and fit your scientific computation needs such as slicing, indexing, math operations, linear algebra, reductions. And they are fast!"


#### Dynamic Graphs!!!

"Most frameworks such as TensorFlow, Theano, Caffe and CNTK have a static view of the world. One has to build a neural network, and reuse the same structure again and again. Changing the way the network behaves means that one has to start from scratch.

With PyTorch, we use a technique called Reverse-mode auto-differentiation, which allows you to change the way your network behaves arbitrarily with zero lag or overhead. Our inspiration comes from several research papers on this topic, as well as current and past work such as autograd, autograd, Chainer, etc.

While this technique is not unique to PyTorch, it’s one of the fastest implementations of it to date. You get the best of speed and flexibility for your crazy research."



## Working with PyTorch Basics

Enough of the sales pitch!  Let's start to understand the PyTorch basics.

The basic unit of PyTorch is a tensor (basically a multi-dimensional array like a np.ndarray).

![](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)

(image borrowed from https://hackernoon.com/learning-ai-if-you-suck-at-math-p4-tensors-illustrated-with-cats-27f0002c9b32 )

We can create PyTorch tensors directly.

In [2]:
# from https://www.stefanfiott.com/machine-learning/tensors-and-gradients-in-pytorch/
def tensor_properties(t, show_value=True):
    print('Tensor properties:')
    props = [('rank', t.dim()),
             ('shape', t.size()),
             ('data type', t.dtype),
             ('tensor type', t.type())]
    for s,v in props:
        print('\t{0:12}: {1}'.format(s,v))
    if show_value:
        #print('{0:12}: {1}'.format('value',t))
        print("Value:")
        print(t)

In [3]:
# torch.tensor always copies data. See below for 0-copy
scalar = torch.tensor(5)
tensor_properties(scalar)

Tensor properties:
	rank        : 0
	shape       : torch.Size([])
	data type   : torch.int64
	tensor type : torch.LongTensor
Value:
tensor(5)


In [4]:
## You can create torch.Tensor objects by giving them data directly

#  1D vector
vector_input = [1., 2., 3., 4., 5., 6.]
vector = torch.tensor(vector_input)
tensor_properties(vector)

Tensor properties:
	rank        : 1
	shape       : torch.Size([6])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([1., 2., 3., 4., 5., 6.])


In [5]:
# Matrix
matrix_input = [[1., 2., 3.], [4., 5., 6]]
matrix = torch.tensor(matrix_input)
tensor_properties(matrix)

Tensor properties:
	rank        : 2
	shape       : torch.Size([2, 3])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# Create a 3D tensor of size 2x2x2.
tensor_input = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
tensor3d = torch.tensor(tensor_input)

tensor_properties(tensor3d)

Tensor properties:
	rank        : 3
	shape       : torch.Size([2, 2, 2])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


They can be created without any initialization or initialized with random data from uniform (rand()) or normal (randn()) distributions

In [7]:
# Tensors with no initialization
x_1 = torch.Tensor(2, 5)
y_1 = torch.Tensor(3, 5)
tensor_properties(x_1)
tensor_properties(y_1)

Tensor properties:
	rank        : 2
	shape       : torch.Size([2, 5])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[0.0000e+00, 0.0000e+00, 4.7242e-30, 1.4013e-45, 1.4013e-45],
        [0.0000e+00,        nan,        nan, 0.0000e+00, 0.0000e+00]])
Tensor properties:
	rank        : 2
	shape       : torch.Size([3, 5])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[0.0000e+00, 2.5244e-29, 2.1424e+18, 3.6902e+19,        nan],
        [4.0009e-01, 2.6539e+20, 1.3720e-05, 8.2287e-10, 3.3237e+21],
        [7.9876e+20, 1.0356e-11, 3.2507e+21, 2.1155e+23, 6.6767e+22]])


In [8]:
# Tensors initialized from uniform
x_2 = torch.rand(5, 3)
y_2 = torch.rand(5, 5)

tensor_properties(x_2)
tensor_properties(y_2)

Tensor properties:
	rank        : 2
	shape       : torch.Size([5, 3])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[0.1731, 0.5860, 0.9408],
        [0.1822, 0.3583, 0.5094],
        [0.9066, 0.1693, 0.5683],
        [0.5692, 0.5983, 0.0565],
        [0.3171, 0.3858, 0.9611]])
Tensor properties:
	rank        : 2
	shape       : torch.Size([5, 5])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[0.8404, 0.0445, 0.2126, 0.7769, 0.4568],
        [0.2210, 0.0576, 0.4617, 0.5757, 0.4886],
        [0.2164, 0.3876, 0.5445, 0.0658, 0.1115],
        [0.3072, 0.2082, 0.6105, 0.2604, 0.3840],
        [0.8354, 0.7122, 0.3983, 0.2591, 0.7418]])


In [9]:
# Tensors initialized from normal
x_3 = torch.randn(5, 3)
y_3 = torch.randn(5, 5)

tensor_properties(x_3)
tensor_properties(y_3)

Tensor properties:
	rank        : 2
	shape       : torch.Size([5, 3])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[ 2.3204,  0.3680, -0.3345],
        [ 0.5786, -0.9157,  1.0126],
        [ 0.0554,  0.1838,  0.3382],
        [-0.4858, -0.1170,  0.4786],
        [-0.1496, -0.1351,  0.5300]])
Tensor properties:
	rank        : 2
	shape       : torch.Size([5, 5])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([[-1.0434,  0.3052, -0.5218, -0.4642,  0.3054],
        [ 0.4403, -0.1521, -0.7880,  1.6518,  0.0804],
        [ 0.4412, -1.4000,  0.6472, -0.5859,  1.4238],
        [-0.0665, -0.5396,  1.2033, -0.6931,  0.1474],
        [-0.9490,  2.5622,  0.6595,  0.8421,  0.2955]])


The expected operations (arithmetic operations, addressing, etc) are all in place.

In [10]:
# Expect (2,5)
print(x_1.size())

print(x_1)


# Addition
print(x_2)
print(x_3)

print(x_2 + x_3)

# Addressing
print(x_3[:, 2])

torch.Size([2, 5])
tensor([[0.0000e+00, 0.0000e+00, 4.7242e-30, 1.4013e-45, 1.4013e-45],
        [0.0000e+00,        nan,        nan, 0.0000e+00, 0.0000e+00]])
tensor([[0.1731, 0.5860, 0.9408],
        [0.1822, 0.3583, 0.5094],
        [0.9066, 0.1693, 0.5683],
        [0.5692, 0.5983, 0.0565],
        [0.3171, 0.3858, 0.9611]])
tensor([[ 2.3204,  0.3680, -0.3345],
        [ 0.5786, -0.9157,  1.0126],
        [ 0.0554,  0.1838,  0.3382],
        [-0.4858, -0.1170,  0.4786],
        [-0.1496, -0.1351,  0.5300]])
tensor([[ 2.4935,  0.9540,  0.6063],
        [ 0.7608, -0.5574,  1.5221],
        [ 0.9620,  0.3530,  0.9065],
        [ 0.0833,  0.4813,  0.5351],
        [ 0.1676,  0.2508,  1.4911]])
tensor([-0.3345,  1.0126,  0.3382,  0.4786,  0.5300])


It's easy to move between PyTorch and Numpy worlds with numpy() and torch.from_numpy()

In [12]:
# PyTorch --> Numpy
print(x_2)
print(x_2.numpy())

print(type(x_2))
print(type(x_2.numpy()))

numpy_x_2 = x_2.numpy()

# does not makes a copy: just wraps a tensor object around the numpy array
pytorch_x_2 = torch.from_numpy(numpy_x_2)

print(type(numpy_x_2))
print(type(pytorch_x_2))

tensor([[0.1731, 0.5860, 0.9408],
        [0.1822, 0.3583, 0.5094],
        [0.9066, 0.1693, 0.5683],
        [0.5692, 0.5983, 0.0565],
        [0.3171, 0.3858, 0.9611]])
[[0.17308003 0.5860269  0.94082624]
 [0.18217129 0.3583225  0.50943184]
 [0.9065808  0.1692515  0.5682808 ]
 [0.5691937  0.598268   0.05651069]
 [0.31713253 0.38583302 0.96105534]]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


Finally PyTorch provides some convenience mechanisms for concatenating Tensors via torch.cat() and reshaping them with  .view() 

In [13]:
## Concatenating

# By default, it concatenates along the zeroth(first) axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1.shape)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2.shape)

## Reshaping
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))

torch.Size([5, 5])
torch.Size([2, 8])
tensor([[[-0.8677,  1.3345,  0.2592,  0.2366],
         [ 1.9499, -2.1314, -2.3725,  1.7007],
         [-1.1011,  0.4278, -0.3607, -0.2124]],

        [[-0.0967, -0.1051,  2.3655, -1.7159],
         [ 0.6802, -0.8794,  0.1641,  1.2874],
         [-1.1696, -0.8046, -1.4742,  0.2795]]])
tensor([[-0.8677,  1.3345,  0.2592,  0.2366,  1.9499, -2.1314, -2.3725,  1.7007,
         -1.1011,  0.4278, -0.3607, -0.2124],
        [-0.0967, -0.1051,  2.3655, -1.7159,  0.6802, -0.8794,  0.1641,  1.2874,
         -1.1696, -0.8046, -1.4742,  0.2795]])
tensor([[-0.8677,  1.3345,  0.2592,  0.2366,  1.9499, -2.1314, -2.3725,  1.7007,
         -1.1011,  0.4278, -0.3607, -0.2124],
        [-0.0967, -0.1051,  2.3655, -1.7159,  0.6802, -0.8794,  0.1641,  1.2874,
         -1.1696, -0.8046, -1.4742,  0.2795]])


## PyTorch Variables and the Computational Graph

Ok -- back to PyTorch.

The other fundamental PyTorch construct besides Tensors are Variables.  Variables are very similar to tensors, but they also keep track of the graph (including their gradients for autodifferentiation).  They are defined in the autograd module of torch.

This has changed in recent versions of pytorch, but i want to keep this section in as you will likely see code which uses `Variables`. A `Variable` bow is just a tensor with `requires_grad=True`.

In [14]:
from torch.autograd import Variable
import torch.nn as nn

# Let's create a variable by initializing it with a tensor
first_tensor = torch.Tensor([23.3])

In [15]:
tensor_properties(first_tensor)

Tensor properties:
	rank        : 1
	shape       : torch.Size([1])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([23.3000])


In [16]:
print("first_tensor.grad", first_tensor.grad)

first_tensor.grad None


In [17]:
first_variable = Variable(first_tensor, requires_grad=True)

print("first variables gradient: ", first_variable.grad)
print("first variables data: ", first_variable.data)

first variables gradient:  None
first variables data:  tensor([23.3000])


In [18]:
tensor_properties(first_tensor)

Tensor properties:
	rank        : 1
	shape       : torch.Size([1])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([23.3000])


In [19]:
first_tensor_new = torch.tensor([23.3], requires_grad=True)

In [69]:
tensor_properties(first_tensor_new)

Tensor properties:
	rank        : 1
	shape       : torch.Size([1])
	data type   : torch.float32
	tensor type : torch.FloatTensor
Value:
tensor([23.3000], requires_grad=True)


In [20]:
x = first_tensor_new
print("x.data", x.data)
y = (x ** x) * (x - 2) # y is a variable
z = torch.tanh(y) # z has a functional relationship to y
print("z.grad: ", z.grad)

z.backward()

print("y.data: ", y.data)
print("y.grad: ", y.grad)

print("z.data: ", z.data)
print("z.grad: ", z.grad)

print("x.grad:", x.grad)



x.data tensor([23.3000])
z.grad:  None
y.data:  tensor([1.5409e+33])
y.grad:  None
z.data:  tensor([1.])
z.grad:  None
x.grad: tensor([0.])


Variables (and now tensors requiring gradients) come with a .backward() that allows them to do autodifferentiation via backwards propagation.  